# Generated by Django 3.0.6 on 2020-05-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coeff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff_zero', models.DecimalField(decimal_places=9, default=1, max_digits=19)),
                ('coeff_one', models.DecimalField(decimal_places=9, default=1, max_digits=19)),
                ('coeff_two', models.DecimalField(decimal_places=9, default=1, max_digits=19)),
                ('coeff_three', models.DecimalField(decimal_places=9, default=1, max_digits=19)),
                ('coeff_four', models.DecimalField(decimal_places=9, default=1, max_digits=19)),
                ('coeff_five', models.DecimalField(decimal_places=9, default=1, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(default='', max_length=2500)),
                ('be_subjects', models.IntegerField(default=1)),
                ('aux_subjects', models.IntegerField(default=1)),
                ('question_words', models.IntegerField(default=1)),
                ('verbs', models.IntegerField(default=1)),
                ('subjects', models.IntegerField(default=1)),
                ('sen_type', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(default='', max_length=2500)),
                ('be_subjects', models.IntegerField(default=1)),
                ('aux_subjects', models.IntegerField(default=1)),
                ('question_words', models.IntegerField(default=1)),
                ('verbs', models.IntegerField(default=1)),
                ('subjects', models.IntegerField(default=1)),
                ('sen_type', models.IntegerField(default=1)),
            ],
        ),
    ]
